<h1>Detalles</h1>

<table width="40%;">
	<tr>
		<td>Title</td>
		<td><?php echo $this->results['title']; ?></td>
	</tr>
	<tr>
		<td>Artist</td>
		<td><?php echo $this->results['artist']; ?></td>
	</tr>
	<tr>
		<td>Genre</td>
		<td><?php echo $this->results['genre']; ?></td>
	</tr>
</table>

<div>
	<a href="<?php echo $this->url; ?>/admin/albums/edit/<?php echo $this->results['id']; ?>">Editar</a> 
	<a onclick="return confirmation('<?php echo $this->url; ?>/admin/albums/delete/<?php echo $this->results['id']; ?>','¿Desea eliminar este item?')" href="#">Eliminar</a>
</div>
