<a class="action" href="<?php echo $this->url; ?>/admin/albums">Regresar</a>

<h2>Detalles</h1>

<table>
	<tr>
		<td>Title</td>
		<td><?php echo $this->results['title']; ?></td>
	</tr>
	<tr>
		<td>Artist</td>
		<td><?php echo $this->results['artist']; ?></td>
	</tr>
	<tr>
		<td>Genre</td>
		<td><?php echo $this->results['genre']; ?></td>
	</tr>
</table>

<div>
	<a class="action" href="<?php echo $this->url; ?>/admin/albums/edit/<?php echo $this->results['id']; ?>">Editar</a> 
	<a class="action" onclick="return _confirm('<?php echo $this->url; ?>/admin/albums/delete/<?php echo $this->results['id']; ?>')" href="#">Eliminar</a>
</div>

<script type="text/javascript">
	function _confirm(url) {
		var agree = confirm("¿Deseas eliminar este item?");
		if (agree) {
			document.location.href= url;
		} else {
			return false ;
		}
		
	}
</script>
