<!DOCTYPE html>
<head>
	<meta charset="UTF-8" />
	<meta name="description" content="" />
	<meta name="keywords" content="" />
	<meta name="author" content="">
	<?php
		echo $this->headTitle(). "\n";
		echo $this->headScript(). "\n";
        echo $this->headLink(). "\n";
	?>
	<link href="<?php echo $this->url; ?>/favicon.ico" rel="shortcut icon">
	<link href="<?php echo $this->url; ?>/css/main.css" rel="stylesheet">
</head>
<body>

<header>

</header>

<div class="wrap">
	<?php echo $this->layout()->content; ?>
</div>


<footer>
	
</footer>

</body>
</html>
