<?php ?>

<form action="" method="get">
	<fieldset>
		<legend>Buscar</legend>
		<input type="text" name="q" />
		<input type="submit" value="search" />
	</fieldset>
</form>

<table>
 <tr>
 	<td><strong>Title</strong></td>
 	<td><strong>Artist</strong></td>
 	<td><strong>Genre</strong></td>
 </tr>
 <?php foreach ($this->results as $row): ?>
 <tr>
 	<td><?php echo $row['title']; ?></td>
 	<td><?php echo $row['artist']; ?></td>
 	<td><?php echo $row['genre']; ?></td>
 </tr>
 <?php endforeach; ?>
</table>